/**
 * Finance PDF engine — reuses the same professional design as pdf.ts.
 * All hotel details come from HotelSettings — nothing is hardcoded.
 */

import jsPDF from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import type { HotelSettings } from './types';
import type { ExpenseEntry, MonthlyProfitability } from './types-finance';
import { fmtMoney, toNum } from './calc';

// ── Colour palette (matches pdf.ts) ──────────────────────────────────────────
const C = {
  headerBg:    [13, 71, 109]  as [number, number, number],
  headerText:  [255, 255, 255] as [number, number, number],
  sectionBg:   [32, 101, 149] as [number, number, number],
  sectionText: [255, 255, 255] as [number, number, number],
  altRow:      [240, 247, 253] as [number, number, number],
  footBg:      [230, 242, 250] as [number, number, number],
  footText:    [13, 71, 109]  as [number, number, number],
  border:      [189, 215, 235] as [number, number, number],
  text:        [30, 30, 30]   as [number, number, number],
  muted:       [100, 100, 100] as [number, number, number],
  accent:      [215, 38, 38]  as [number, number, number],
};

const rs = (n: number): string => `Rs.${fmtMoney(n)}`;
const fmtDate = (iso: string | null | undefined): string => {
  if (!iso) return '—';
  const [y, m, d] = iso.split('-');
  return `${d}/${m}/${y}`;
};

const now = () => {
  const d = new Date();
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
       + ' ' + d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
};

// ── Shared header (duplicated from pdf.ts for module independence) ────────────
async function loadImageDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

async function drawPageHeader(
  doc: jsPDF,
  settings: HotelSettings,
  reportTitle: string,
  reportSubtitle: string,
  landscape: boolean,
) {
  const pw = landscape ? 297 : 210;
  const lm = 14;
  const LOGO_SIZE = 18;
  const logoX = lm;
  const textX = settings.logo_url ? lm + LOGO_SIZE + 3 : lm;

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, pw, 30, 'F');

  if (settings.logo_url) {
    try {
      const dataUrl = await loadImageDataUrl(settings.logo_url);
      if (dataUrl) doc.addImage(dataUrl, logoX, 6, LOGO_SIZE, LOGO_SIZE);
    } catch { /* ignore */ }
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...C.headerText);
  doc.text(settings.hotel_name || 'Hotel', textX, 12);

  const addrParts: string[] = [];
  if (settings.address) addrParts.push(settings.address);
  if (settings.city) addrParts.push(settings.city);
  if (settings.state_name) addrParts.push(settings.state_name);
  if (settings.pin_code) addrParts.push(settings.pin_code);
  const addrLine = addrParts.join(', ');

  const contactParts: string[] = [];
  if (settings.phone) contactParts.push(`Ph: ${settings.phone}`);
  if (settings.email) contactParts.push(settings.email);
  if (settings.website) contactParts.push(settings.website);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...C.headerText);
  if (addrLine) doc.text(addrLine, textX, 18.5);
  if (contactParts.length) doc.text(contactParts.join('  |  '), textX, addrLine ? 23 : 18.5);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...C.headerText);
  doc.text(reportTitle, pw - lm, 12, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(reportSubtitle, pw - lm, 18.5, { align: 'right' });

  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.4);
  doc.line(0, 30, pw, 30);

  // Reset text color to dark so subsequent autoTable calls don't inherit white
  doc.setTextColor(...C.text);
  doc.setFont('helvetica', 'normal');
}

function addPageFooters(doc: jsPDF, landscape: boolean) {
  const totalPages = (doc as jsPDF & { internal: { getNumberOfPages: () => number } })
    .internal.getNumberOfPages();
  const pw = landscape ? 297 : 210;
  const ph = landscape ? 210 : 297;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(...C.footBg);
    doc.rect(0, ph - 10, pw, 10, 'F');
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(...C.muted);
    doc.text(`Generated: ${now()}`, 14, ph - 3.5);
    doc.text(`Page ${i} of ${totalPages}`, pw - 14, ph - 3.5, { align: 'right' });
    doc.text('Generated by Hotel Mantri  |  Your Hotel\'s Digital Manager', pw / 2, ph - 3.5, { align: 'center' });
  }
}

function sectionHead(doc: jsPDF, text: string, y: number, landscape: boolean): number {
  const pw = landscape ? 297 : 210;
  doc.setFillColor(...C.sectionBg);
  doc.rect(14, y, pw - 28, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...C.sectionText);
  doc.text(text, 17, y + 4.8);
  doc.setTextColor(...C.text);
  return y + 10;
}

// ────────────────────────────────────────────────────────────────────────────
// 1. EXPENSE LEDGER PDF
// ────────────────────────────────────────────────────────────────────────────
export interface ExpenseLedgerPDFOpts {
  settings: HotelSettings;
  entries: ExpenseEntry[];
  fromDate: string;
  toDate: string;
}

export async function buildExpenseLedgerPDF(opts: ExpenseLedgerPDFOpts): Promise<jsPDF> {
  const { settings, entries, fromDate, toDate } = opts;
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  await drawPageHeader(doc, settings, 'Expense Ledger', `${fmtDate(fromDate)} to ${fmtDate(toDate)}`, true);

  let total = 0, cash = 0, bank = 0, upi = 0, credit = 0;
  const catMap = new Map<string, number>();
  for (const e of entries) {
    const amt = toNum(e.amount);
    total += amt;
    if (e.payment_mode === 'Cash') cash += amt;
    else if (e.payment_mode === 'Bank') bank += amt;
    else if (e.payment_mode === 'UPI') upi += amt;
    else if (e.payment_mode === 'Credit') credit += amt;
    catMap.set(e.category_name, (catMap.get(e.category_name) ?? 0) + amt);
  }

  autoTable(doc, {
    startY: 36,
    margin: { left: 10, right: 10 },
    head: [['Date', 'Expense Head', 'Description', 'Bill No.', 'Payment Mode', 'Amount']],
    body: entries.map((e) => [
      fmtDate(e.entry_date),
      String(e.category_name || '—'),
      String(e.description || '—'),
      String(e.bill_no || '—'),
      String(e.payment_mode || '—') + (e.is_paid ? '' : ' (Unpaid)'),
      rs(toNum(e.amount)),
    ]),
    foot: [[
      `Total: ${rs(total)}`, '', '', '', '',
      `Cash: ${rs(cash)}  Bank: ${rs(bank)}  UPI: ${rs(upi)}  Credit: ${rs(credit)}`,
    ]],
    showFoot: 'lastPage',
    theme: 'grid',
    columnStyles: {
      0: { cellWidth: 22, overflow: 'linebreak' },
      1: { cellWidth: 38, overflow: 'linebreak' },
      2: { cellWidth: 'auto', overflow: 'linebreak' },
      3: { cellWidth: 26, overflow: 'linebreak' },
      4: { cellWidth: 30, overflow: 'linebreak' },
      5: { cellWidth: 30, halign: 'right', overflow: 'linebreak' },
    },
    styles: { fontSize: 8, cellPadding: 2.5, lineColor: C.border, lineWidth: 0.2, textColor: C.text, overflow: 'linebreak' },
    headStyles: { fillColor: C.sectionBg, textColor: C.sectionText, fontSize: 8.5, fontStyle: 'bold' },
    footStyles: { fillColor: C.footBg, textColor: C.footText, fontStyle: 'bold', fontSize: 8 },
    alternateRowStyles: { fillColor: C.altRow },
  });

  // Category summary on new page
  doc.addPage();
  let y = 36;
  y = sectionHead(doc, 'Category Summary', y, true);
  autoTable(doc, {
    startY: y,
    margin: { left: 10, right: 10 },
    head: [['Expense Head', 'Amount']],
    body: Array.from(catMap.entries()).sort((a, b) => b[1] - a[1]).map(([cat, amt]) => [String(cat), rs(amt)]),
    foot: [['Total', rs(total)]],
    showFoot: 'lastPage',
    theme: 'grid',
    columnStyles: { 0: { cellWidth: 'auto', overflow: 'linebreak' }, 1: { cellWidth: 50, halign: 'right', overflow: 'linebreak' } },
    styles: { fontSize: 9, cellPadding: 3, lineColor: C.border, lineWidth: 0.2, textColor: C.text, overflow: 'linebreak' },
    headStyles: { fillColor: C.sectionBg, textColor: C.sectionText, fontStyle: 'bold' },
    footStyles: { fillColor: C.footBg, textColor: C.footText, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: C.altRow },
  });

  addPageFooters(doc, true);
  return doc;
}

// ────────────────────────────────────────────────────────────────────────────
// 2. MONTHLY PROFITABILITY PDF
// ────────────────────────────────────────────────────────────────────────────
export interface MonthlyProfitabilityPDFOpts {
  settings: HotelSettings;
  data: MonthlyProfitability;
}

export async function buildMonthlyProfitabilityPDF(opts: MonthlyProfitabilityPDFOpts): Promise<jsPDF> {
  const { settings, data } = opts;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const [y, m] = data.month_key.split('-');
  const monthName = new Date(parseInt(y, 10), parseInt(m, 10) - 1, 1)
    .toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });

  await drawPageHeader(doc, settings, 'Monthly Profitability', monthName, false);

  let yy = 36;

  // Revenue section
  yy = sectionHead(doc, 'Revenue', yy, false);
  autoTable(doc, {
    startY: yy,
    margin: { left: 14, right: 14 },
    head: [['Revenue Head', 'Amount']],
    body: [
      ['Room Revenue', rs(data.room_revenue)],
      ['F&B Revenue', rs(data.fb_revenue)],
      ['Laundry Revenue', rs(data.laundry_revenue)],
      ['Other Revenue', rs(data.other_revenue)],
    ],
    foot: [['Total Revenue', rs(data.total_revenue)]],
    showFoot: 'lastPage',
    columnStyles: { 0: { cellWidth: 'auto' }, 1: { cellWidth: 50, halign: 'right' } },
    styles: { fontSize: 9, cellPadding: 3, lineColor: C.border, lineWidth: 0.2 },
    headStyles: { fillColor: C.sectionBg, textColor: C.sectionText },
    footStyles: { fillColor: C.footBg, textColor: C.footText, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: C.altRow },
  });
  yy = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 4;

  // Expense section
  yy = sectionHead(doc, 'Expenses', yy, false);
  autoTable(doc, {
    startY: yy,
    margin: { left: 14, right: 14 },
    head: [['Expense Head', 'Amount']],
    body: [
      ['Salary', rs(data.salary_expense)],
      ...data.expense_by_category.map((c) => [c.category, rs(c.amount)] as [string, string]),
    ],
    foot: [['Total Expenses', rs(data.total_expenses)]],
    showFoot: 'lastPage',
    columnStyles: { 0: { cellWidth: 'auto' }, 1: { cellWidth: 50, halign: 'right' } },
    styles: { fontSize: 9, cellPadding: 3, lineColor: C.border, lineWidth: 0.2 },
    headStyles: { fillColor: C.sectionBg, textColor: C.sectionText },
    footStyles: { fillColor: C.footBg, textColor: C.footText, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: C.altRow },
  });
  yy = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 4;

  // Cash Summary section — matches WhatsApp report
  yy = sectionHead(doc, 'Cash Summary', yy, false);
  autoTable(doc, {
    startY: yy,
    margin: { left: 14, right: 14 },
    head: [['Cash Head', 'Amount']],
    body: [
      ['Cash', rs(data.cash)],
      ['Bank', rs(data.bank)],
      ['Salary Advance', rs(data.salary_advance)],
      ['Cash Handover MD Sir', rs(data.cash_handover_md)],
      ['Bank Cash Deposit', rs(data.bank_cash_deposit)],
      ['Cash Closing', rs(data.cash_closing)],
    ],
    columnStyles: { 0: { cellWidth: 'auto' }, 1: { cellWidth: 50, halign: 'right' } },
    styles: { fontSize: 9, cellPadding: 3, lineColor: C.border, lineWidth: 0.2 },
    headStyles: { fillColor: C.sectionBg, textColor: C.sectionText },
    alternateRowStyles: { fillColor: C.altRow },
    theme: 'grid',
    didParseCell(d) {
      if (d.row.index === 5) { // Cash Closing row
        d.cell.styles.fillColor = C.footBg;
        d.cell.styles.fontStyle = 'bold';
        d.cell.styles.textColor = C.footText;
      }
    },
  });
  yy = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 4;

  // Result section
  yy = sectionHead(doc, 'Result', yy, false);
  const margin = data.profit_margin.toFixed(1);
  autoTable(doc, {
    startY: yy,
    margin: { left: 14, right: 14 },
    head: [],
    body: [
      ['Total Revenue', rs(data.total_revenue)],
      ['Total Expenses', rs(data.total_expenses)],
      ['Net Operating Profit', rs(data.net_operating_profit)],
      ['Profit Margin', `${margin} %`],
    ],
    columnStyles: {
      0: { cellWidth: 120, fontStyle: 'normal', textColor: C.muted, fontSize: 10 },
      1: { fontStyle: 'bold', textColor: C.text, fontSize: 10, halign: 'right' },
    },
    styles: { cellPadding: 4, lineColor: C.border, lineWidth: 0.2 },
    theme: 'plain',
    didParseCell(d) {
      if (typeof d.cell.raw === 'string' && /Net Operating|Profit Margin/.test(d.cell.raw as string)) {
        d.cell.styles.fillColor = C.footBg;
        d.cell.styles.fontStyle = 'bold';
        d.cell.styles.textColor = C.footText;
      }
    },
  });

  addPageFooters(doc, false);
  return doc;
}
