ALTER TABLE hotel_settings
  ADD COLUMN IF NOT EXISTS legal_name         text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city               text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state_name         text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pin_code           text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS whatsapp_number    text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS website            text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gst_number         text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pan_number         text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hotel_reg_number   text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cin_number         text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS manager_name       text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS manager_mobile     text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS admin_name         text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_name          text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS account_name       text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS account_number     text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ifsc_code          text NOT NULL DEFAULT '';
